<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto3/albia.proto

/**
 * Protobuf enum <code>DeviceRecord.RecordType</code>
 */
class DeviceRecord_RecordType
{
    /**
     * <code>DOUBLE = 0;</code>
     */
    const DOUBLE = 0;
    /**
     * <code>FLOAT = 1;</code>
     */
    const FLOAT = 1;
    /**
     * <code>INT32 = 2;</code>
     */
    const INT32 = 2;
    /**
     * <code>INT64 = 3;</code>
     */
    const INT64 = 3;
    /**
     * <code>UINT32 = 4;</code>
     */
    const UINT32 = 4;
    /**
     * <code>UINT64 = 5;</code>
     */
    const UINT64 = 5;
    /**
     * <code>BOOL = 6;</code>
     */
    const BOOL = 6;
    /**
     * <code>STRING = 7;</code>
     */
    const STRING = 7;
    /**
     * <code>BYTES = 8;</code>
     */
    const BYTES = 8;
}

