<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto3/albia.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>DeviceEventMsg</code>
 */
class DeviceEventMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string action = 1;</code>
     */
    private $action = '';
    /**
     * <code>uint32 deviceId = 2;</code>
     */
    private $deviceId = 0;
    /**
     * <code>uint32 targetDeviceId = 3;</code>
     */
    private $targetDeviceId = 0;
    /**
     * <code>.google.protobuf.Timestamp date = 4;</code>
     */
    private $date = null;
    /**
     * <code>string data = 5;</code>
     */
    private $data = '';

    public function __construct() {
        \GPBMetadata\Proto3\Albia::initOnce();
        parent::__construct();
    }

    /**
     * <code>string action = 1;</code>
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * <code>string action = 1;</code>
     */
    public function setAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->action = $var;
    }

    /**
     * <code>uint32 deviceId = 2;</code>
     */
    public function getDeviceId()
    {
        return $this->deviceId;
    }

    /**
     * <code>uint32 deviceId = 2;</code>
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkUint32($var);
        $this->deviceId = $var;
    }

    /**
     * <code>uint32 targetDeviceId = 3;</code>
     */
    public function getTargetDeviceId()
    {
        return $this->targetDeviceId;
    }

    /**
     * <code>uint32 targetDeviceId = 3;</code>
     */
    public function setTargetDeviceId($var)
    {
        GPBUtil::checkUint32($var);
        $this->targetDeviceId = $var;
    }

    /**
     * <code>.google.protobuf.Timestamp date = 4;</code>
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * <code>.google.protobuf.Timestamp date = 4;</code>
     */
    public function setDate(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->date = $var;
    }

    /**
     * <code>string data = 5;</code>
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * <code>string data = 5;</code>
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->data = $var;
    }

}

