<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto3/timestamp.proto

namespace GPBMetadata\Proto3;

class Timestamp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ade010a1670726f746f332f74696d657374616d702e70726f746f120f67" .
            "6f6f676c652e70726f746f627566222b0a0954696d657374616d70120f0a" .
            "077365636f6e6473180120012803120d0a056e616e6f7318022001280542" .
            "7e0a13636f6d2e676f6f676c652e70726f746f627566420e54696d657374" .
            "616d7050726f746f50015a2b6769746875622e636f6d2f676f6c616e672f" .
            "70726f746f6275662f7074797065732f74696d657374616d70f80101a202" .
            "03475042aa021e476f6f676c652e50726f746f6275662e57656c6c4b6e6f" .
            "776e5479706573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

