<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'duncan3dc\\Forker\\' => array($vendorDir . '/duncan3dc/fork-helper/src'),
    'duncan3dc\\ForkerTests\\' => array($vendorDir . '/duncan3dc/fork-helper/tests'),
);
