<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbc92fec214aaaa46c0f675e79afa503b
{
    public static $prefixLengthsPsr4 = array (
        'd' => 
        array (
            'duncan3dc\\Forker\\' => 17,
            'duncan3dc\\ForkerTests\\' => 22,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'duncan3dc\\Forker\\' => 
        array (
            0 => __DIR__ . '/..' . '/duncan3dc/fork-helper/src',
        ),
        'duncan3dc\\ForkerTests\\' => 
        array (
            0 => __DIR__ . '/..' . '/duncan3dc/fork-helper/tests',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbc92fec214aaaa46c0f675e79afa503b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbc92fec214aaaa46c0f675e79afa503b::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
